source 'https://rubygems.org'

gem 'sinatra', '~> 1.3.2'
gem 'sfcsfs',  '~> 0.1.1'
gem 'haml'
gem 'less'
gem 'coffee-script'
gem 'sequel'
gem 'sqlite3'
gem 'bundler'
gem 'therubyracer'
gem 'pit'
gem 'twitter'
